services:
  selenoid:
    build:
      context: ./selenoid
      dockerfile: Dockerfile.selenoid

    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["-conf", "/etc/selenoid/config/browsers.json"]

  tests:
    build: .
    depends_on:
      - selenoid
    environment:
      - SELENOID_HOST=http://selenoid:4444
      - SELENOID_URL=http://selenoid:4444
      - PYTHONUNBUFFERED=1
    volumes:
      - ./allure-results:/app/allure-results
    command: ["/bin/bash", "/app/bash_scripts/selenoid_run.sh"]
